technologies:
  go:
    name: "Go"
    version_command: ["go", "version"]
    benchmarks:
      http_server:
        command: ["go", "run", "benchmarks/go/http_server/main.go"]
        type: "server"
        port: 3000
      file_read:
        command: ["go", "run", "benchmarks/go/file_read/main.go"]
        type: "benchmark"
        default_params:
          file: "test_data/medium.txt"
          iterations: "1000"
      file_write:
        command: ["go", "run", "benchmarks/go/file_write/main.go"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output.txt"
          iterations: "1000"
          size: "1024"
      file_read_lines:
        command: ["go", "run", "benchmarks/go/file_read_lines/main.go"]
        type: "benchmark"
        default_params:
          file: "test_data/xlarge_lines.txt"
          iterations: "10"
      file_write_lines:
        command: ["go", "run", "benchmarks/go/file_write_lines/main.go"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output_lines.txt"
          iterations: "10"
          lines: "1000000"
      json_write:
        command: ["go", "run", "benchmarks/go/json_write/main.go"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output.json"
          iterations: "1000"
          size: "100"
      json_read_lines:
        command: ["go", "run", "benchmarks/go/json_read_lines/main.go"]
        type: "benchmark"
        default_params:
          file: "test_data/xlarge_lines.json"
          iterations: "10"
      json_write_lines:
        command: ["go", "run", "benchmarks/go/json_write_lines/main.go"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output_lines.json"
          iterations: "10"
          lines: "1000000"
      concurrency_test:
        command: ["go", "run", "benchmarks/go/concurrency_test/main.go"]
        type: "benchmark"
        default_params:
          mode: "single"
          workload: "1000000"
      cold_start:
        command: ["go", "run", "benchmarks/go/cold_start/main.go"]
        type: "benchmark"
        default_params:
          port: "3000"
          iterations: "10"
          timeout: "5000"
      concurrency_limit:
        command: ["go", "run", "benchmarks/go/concurrency_limit/main.go"]
        type: "benchmark"
        default_params:
          port: "3000"
          start-clients: "10"
          max-clients: "300"
          step-size: "25"
          duration: "10"
          threshold: "50"

  bun:
    name: "Bun"
    version_command: ["bun", "--version"]
    benchmarks:
      http_server:
        command: ["bun", "run", "benchmarks/bun/http_server/index.ts"]
        type: "server"
        port: 3002
      file_read:
        command: ["bun", "run", "benchmarks/bun/file_read/index.ts"]
        type: "benchmark"
        default_params:
          file: "test_data/medium.txt"
          iterations: "1000"
      file_write:
        command: ["bun", "run", "benchmarks/bun/file_write/index.ts"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output.txt"
          iterations: "1000"
          size: "1024"
      file_read_lines:
        command: ["bun", "run", "benchmarks/bun/file_read_lines/index.ts"]
        type: "benchmark"
        default_params:
          file: "test_data/xlarge_lines.txt"
          iterations: "10"
      file_write_lines:
        command: ["bun", "run", "benchmarks/bun/file_write_lines/index.ts"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output_lines.txt"
          iterations: "10"
          lines: "1000000"
      json_write:
        command: ["bun", "run", "benchmarks/bun/json_write/index.ts"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output.json"
          iterations: "1000"
          size: "100"
      json_read_lines:
        command: ["bun", "run", "benchmarks/bun/json_read_lines/index.ts"]
        type: "benchmark"
        default_params:
          file: "test_data/xlarge_lines.json"
          iterations: "10"
      json_write_lines:
        command: ["bun", "run", "benchmarks/bun/json_write_lines/index.ts"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output_lines.json"
          iterations: "10"
          lines: "1000000"
      concurrency_test:
        command: ["bun", "run", "benchmarks/bun/concurrency_test/index.ts"]
        type: "benchmark"
        default_params:
          mode: "single"
          workload: "1000000"
      cold_start:
        command: ["bun", "run", "benchmarks/bun/cold_start/index.ts"]
        type: "benchmark"
        default_params:
          port: "3002"
          iterations: "10"
          timeout: "5000"
      concurrency_limit:
        command: ["bun", "run", "benchmarks/bun/concurrency_limit/index.ts"]
        type: "benchmark"
        default_params:
          port: "3002"
          start-clients: "10"
          max-clients: "300"
          step-size: "25"
          duration: "10"
          threshold: "50"

  node:
    name: "Node.js"
    version_command: ["node", "--version"]
    benchmarks:
      http_server:
        command: ["node", "benchmarks/node/http_server/index.js"]
        type: "server"
        port: 3001
      file_read:
        command: ["node", "benchmarks/node/file_read/index.js"]
        type: "benchmark"
        default_params:
          file: "test_data/medium.txt"
          iterations: "1000"
      file_write:
        command: ["node", "benchmarks/node/file_write/index.js"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output.txt"
          iterations: "1000"
          size: "1024"
      file_read_lines:
        command: ["node", "benchmarks/node/file_read_lines/index.js"]
        type: "benchmark"
        default_params:
          file: "test_data/xlarge_lines.txt"
          iterations: "10"
      file_write_lines:
        command: ["node", "benchmarks/node/file_write_lines/index.js"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output_lines.txt"
          iterations: "10"
          lines: "1000000"
      json_write:
        command: ["node", "benchmarks/node/json_write/index.js"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output.json"
          iterations: "1000"
          size: "100"
      json_read_lines:
        command: ["node", "benchmarks/node/json_read_lines/index.js"]
        type: "benchmark"
        default_params:
          file: "test_data/xlarge_lines.json"
          iterations: "10"
      json_write_lines:
        command: ["node", "benchmarks/node/json_write_lines/index.js"]
        type: "benchmark"
        default_params:
          output: "test_data/temp_output_lines.json"
          iterations: "10"
          lines: "1000000"
      concurrency_test:
        command: ["node", "benchmarks/node/concurrency_test/index.js"]
        type: "benchmark"
        default_params:
          mode: "single"
          workload: "1000000"
      cold_start:
        command: ["node", "benchmarks/node/cold_start/index.js"]
        type: "benchmark"
        default_params:
          port: "3001"
          iterations: "10"
          timeout: "5000"
      concurrency_limit:
        command: ["node", "benchmarks/node/concurrency_limit/index.js"]
        type: "benchmark"
        default_params:
          port: "3001"
          start-clients: "10"
          max-clients: "300"
          step-size: "25"
          duration: "10"
          threshold: "50"

  hono-bun:
    name: "Hono.js on Bun"
    version_command: ["bun", "--version"]
    benchmarks:
      http_server:
        command: ["bun", "run", "benchmarks/hono-bun/http_server/index.ts"]
        type: "server"
        port: 3000

  hono-node:
    name: "Hono.js on Node.js"
    version_command: ["node", "--version"]
    benchmarks:
      http_server:
        command: ["node", "benchmarks/hono-node/http_server/index.js"]
        type: "server"
        port: 3000

  nextjs-fastify:
    name: "Next.js with Fastify"
    version_command: ["node", "--version"]
    benchmarks:
      http_server:
        command: ["node", "benchmarks/nextjs-fastify/http_server/index.js"]
        type: "server"
        port: 3000

  nextjs-express:
    name: "Next.js with Express"
    version_command: ["node", "--version"]
    benchmarks:
      http_server:
        command: ["node", "benchmarks/nextjs-express/http_server/index.js"]
        type: "server"
        port: 3000

  nestjs-express:
    name: "NestJS with Express"
    version_command: ["node", "--version"]
    benchmarks:
      http_server:
        command: ["node", "benchmarks/nestjs-express/http_server/index.js"]
        type: "server"
        port: 3000

  nestjs-fastify:
    name: "NestJS with Fastify"
    version_command: ["node", "--version"]
    benchmarks:
      http_server:
        command: ["node", "benchmarks/nestjs-fastify/http_server/index.js"]
        type: "server"
        port: 3000

# Example of how to add a new technology:
# python:
#   name: "Python"
#   version_command: ["python", "--version"]
#   benchmarks:
#     http_server:
#       command: ["python", "benchmarks/python/http_server/main.py"]
#       type: "server"
#       port: 3000
#     file_read:
#       command: ["python", "benchmarks/python/file_read/main.py"]
#       type: "benchmark"
#       default_params:
#         file: "test_data/medium.txt"
#         iterations: "1000"
#     file_write:
#       command: ["python", "benchmarks/python/file_write/main.py"]
#       type: "benchmark"
#       default_params:
#         output: "test_data/temp_output.txt"
#         iterations: "1000"
#         size: "1024"
#     json_write:
#       command: ["python", "benchmarks/python/json_write/main.py"]
#       type: "benchmark"
#       default_params:
#         output: "test_data/temp_output.json"
#         iterations: "1000"
#         size: "100"
#     concurrency_test:
#       command: ["python", "benchmarks/python/concurrency_test/main.py"]
#       type: "benchmark"
#       default_params:
#         mode: "single"
#         workload: "1000000"

# rust:
#   name: "Rust"
#   version_command: ["rustc", "--version"]
#   benchmarks:
#     http_server:
#       command: ["cargo", "run", "--release", "--bin", "http_server"]
#       type: "server"
#       port: 3000
#     file_read:
#       command: ["cargo", "run", "--release", "--bin", "file_read"]
#       type: "benchmark"
#       default_params:
#         file: "test_data/medium.txt"
#         iterations: "1000" 