name: Run Benchmarks

on:
  push:
    branches: [workflow]
  pull_request:
    branches: [workflow]
  schedule:
    - cron: '0 0 26 * *' # monthly
  workflow_dispatch:
    inputs:
      techs:
        description: 'Technologies to benchmark'
        required: false
        type: choice
        options:
          - all
          - go
          - bun
          - node
        default: all

jobs:
  clean-reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete all reports
        run: rm -rf reports/*
      - name: Save empty reports dir
        run: mkdir -p reports

  benchmarks:
    needs: clean-reports
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tech: ${{ fromJson(github.event.inputs.techs || '"all"') == 'all' && '["go","bun","node"]' || format('["{0}"]', github.event.inputs.techs) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "${HOME}/.bun/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          cd orchestrator && go mod tidy
          cd ..
          node scripts/generate_test_data.js
      - name: Build orchestrator
        run: |
          cd orchestrator && go build -o benchmark-cli
      - name: Run benchmarks for ${{ matrix.tech }}
        run: |
          ./orchestrator/benchmark-cli run --tech=${{ matrix.tech }} --test=all
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.tech }}
          path: reports/ 
